exclude: ^(data|.idea|obsolete)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--config=.github/linters/.python-black, --diff]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      # args: [--config=.github/linters/.flake8]
      args: [
        "--max-line-length=88", "--extend-ignore=E203,E501,W503", "--builtins=request"]
      additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: [--sp=.github/linters/.isort.cfg, --diff]
      additional_dependencies:
        - toml

  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
    - id: pylint
      exclude: versioneer.py|lmpy/_version.py
      args: [--rcfile=.github/linters/.python-lint]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      args: ['--convention=google']

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint
      args: ['-v2', '-sgoogle']

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-tabs
        files: \.(py|rst|md)$

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
      - id: setup-cfg-fmt
