version: "3.9"
services:

  bison_task:
    build:
      context: ./.
      target: task
    environment:
      - TASK_APP=span.task.calc_stats
    env_file:
      ./.env.task.conf
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: specnet_task
        awslogs-stream: calc_stats
        # awslogs-group: specnet_calc_stats
        # awslogs-stream: $timestamp
    volumes:
      # bind mount from host machine
      # - "/home/ubuntu/aws_data:/volumes/aws_data"
      # volumes
      - "scratch-path:/scratch-path"

volumes:
  scratch-path:
