version: "3.9"
services:

  bison_task:
    build:
      context: ./.
      target: task
    environment:
      - TASK_APP=specnet.task.calc_stats
    env_file:
      ./.env.task.conf
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-create-group: true
        awslogs-group: specnet_task_calc_stats
        # awslogs-stream: $timestamp
    volumes:
      # volumes
      - "scratch-path:/scratch-path"

volumes:
  scratch-path:
