version: "3.9"
services:
  back-end:
    build:
      context: ./.
      target: back-end
    networks:
      - nginx
    environment:
      - FLASK_APP=lmtrex.flask_app.broker.routes:app
    restart: unless-stopped
    volumes:
      - "scratch-path:/scratch-path"
      - "webpack-output:/volumes/webpack-output"
      - "static-files:/home/specify/lmtrex/frontend/static"

  front-end:
    build:
      context: ./.
      target: front-end
    volumes:
      - "webpack-output:/home/node/dist"

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    depends_on:
      - back-end
      - front-end
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "static-files:/volumes/static-files:ro"
      - "webpack-output:/volumes/webpack-output:ro"

      - "./lmtrex/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./lmtrex/config/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro"
      - "./lmtrex/config/privkey.pem:/etc/letsencrypt/privkey.pem:ro"

volumes:
  scratch-path:
  static-files:
  webpack-output:

networks:
  nginx:
