version: '3.8'
services:

  back-end:
    build:
      context: ./.
      target: back-end
    networks:
      - cherrypy
    environment:
      - PUBLIC_URL='http://localhost'
      - DEVELOPMENT=true
    restart: unless-stopped
    volumes:
      - "scratch-path:/scratch-path"
      - "static-files:/home/specify/lmtrex/frontend/js_src/static"

  front-end:
    build:
      context: ./.
      target: front-end
    volumes:
      - "webpack-output:/home/node/dist"

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    depends_on:
      - back-end
      - front-end
    networks:
      - cherrypy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./lmtrex/config/nginx/common.conf:/etc/nginx/common.conf:ro"

      # Replace "development" with "production" when in production
      - "./lmtrex/config/nginx/development.conf:/etc/nginx/conf.d/default.conf:ro"
      # Uncomment these when in production
      #- "./lmtrex/config/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro"
      #- "./lmtrex/config/privkey.pem:/etc/letsencrypt/privkey.pem:ro"

      - "static-files:/volumes/static-files:ro"
      - "webpack-output:/volumes/webpack-output:ro"

volumes:
  scratch-path:
  static-files:
  webpack-output:

networks:
  cherrypy:
