version: "3.9"
services:

#  analyst:
#    build:
#      context: ./.
#      target: flask
#    networks:
#      - nginx
#    environment:
#      - FLASK_APP=flask_app.analyst:app
#    env_file:
#      ./.env.conf
#    restart: unless-stopped
#    volumes:
#      - "scratch-path:/scratch-path"
#      - "webpack-output:/volumes/webpack-output"
#      - "static-files:/home/specify/frontend/static"

  broker:
    build:
      context: ./.
      target: flask
    networks:
      - nginx
    environment:
      - FLASK_APP=flask_app.broker.routes:app
    env_file:
      ./.env.conf
    restart: unless-stopped
    volumes:
      - "scratch-path:/scratch-path"
      - "webpack-output:/volumes/webpack-output"
      - "static-files:/home/specify/sppy/frontend/static"


  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - broker
      - front-end

    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "static-files:/volumes/static-files:ro"
      - "webpack-output:/volumes/webpack-output:ro"

      - "./static/:/var/www/:ro"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./config/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro"
      - "./config/privkey.pem:/etc/letsencrypt/privkey.pem:ro"


  front-end:
    build:
      context: ./.
      target: front-end
    volumes:
      - "webpack-output:/home/node/dist"

volumes:
  scratch-path:
  static-files:
  webpack-output:

networks:
  nginx:
