version: "3.8"
services:
  back-end:
    build:
      context: ./.
      target: back-end
    networks:
      - cherrypy
    environment:
      - PUBLIC_URL='http://localhost'
      - DEVELOPMENT=true
    restart: unless-stopped
    volumes:
      - "scratch-path:/scratch-path"
      - "static-files:/home/specify/lmtrex/frontend/static"
      - "webpack-output:/home/specify/lmtrex/frontend/js_src/dist"
      - "./lmtrex/:/home/specify/lmtrex/"

  front-end:
    build:
      context: ./.
      target: front-end
    restart: unless-stopped
    command: npm run watch
    volumes:
      - "webpack-output:/home/node/dist"
      - "./lmtrex/frontend/js_src/:/home/node/"

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    depends_on:
      - back-end
      - front-end
    networks:
      - cherrypy
    ports:
      - "80:80"
    volumes:
      - "static-files:/volumes/static-files:ro"
      - "./lmtrex/config/nginx/common.conf:/etc/nginx/common.conf:ro"

      - "./lmtrex/config/nginx/development.conf:/etc/nginx/conf.d/default.conf:ro"
      - "webpack-output:/volumes/webpack-output:ro"

volumes:
  scratch-path:
  static-files:
  webpack-output:

networks:
  cherrypy:
