version: "3.9"
services:
  back-end:
    build:
      context: ./.
      target: back-end
    networks:
      - cherrypy
    environment:
      - DEVELOPMENT=true
    restart: unless-stopped
    volumes:
      - "scratch-path:/scratch-path"
      - "webpack-output:/home/specify/lmtrex/frontend/js_src/dist"
      - "./lmtrex/:/home/specify/lmtrex/"

  front-end:
    build:
      context: ./.
      target: dev-front-end
    restart: unless-stopped
    volumes:
      - "webpack-output:/home/node/dist"
      - "./lmtrex/frontend/js_src/:/home/node/"

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    depends_on:
      - back-end
      - front-end
    networks:
      - cherrypy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./lmtrex/frontend/static:/volumes/static-files:ro"
      - "./lmtrex/config/nginx/common.conf:/etc/nginx/common.conf:ro"

      - "webpack-output:/volumes/webpack-output:ro"

      - "./lmtrex/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./lmtrex/config/fullchain.pem:/etc/letsencrypt/fullchain.pem:ro"
      - "./lmtrex/config/privkey.pem:/etc/letsencrypt/privkey.pem:ro"

volumes:
  scratch-path:
  webpack-output:

networks:
  cherrypy:
