version: "3.9"
services:

  broker:
    build:
      context: ./.
      target: dev-flask
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=flask_app.broker:app
      - FLASK_MANAGE=flask_app.broker.manage
      - DEBUG_PORT=5003
    volumes:
      - "./flask_app/:/home/specify/flask_app/"

  front-end:
    build:
      context: ./.
      target: base-front-end
    command: ["npm", "run", "watch"]
    volumes:
      - "./sppy/frontend/js_src/lib/:/home/node/lib/"
